@host = http://localhost:3030

get {{host}}/thresholds

###

get {{host}}/thresholds/2


###

put {{host}}/thresholds/2
content-type: application/json

{
    "threshold_level": 30,
    "expiration_date": "2022-05-23T00:00:00.000Z",
    "ref_equipment": 275252783
}

