@host = http://localhost:3030

get {{host}}/users

###

get {{host}}/users/1

###

post {{host}}/users/new
content-type: application/json

{
    "first_name": "Dave",
    "last_name": "Galbe",
    "email": "davetest.com",
    "password": "junior/2",
    "role": "Admin",
    "notes": "In full charge"
}

###

put {{host}}/users/1
content-type: application/json

{
    "first_name": "Terry",
    "last_name": "Badass",
    "email": "terrybadass@badass.com",
    "password": "badass",
    "role": "Admin",
    "notes": "Badass Admin"
}

###

delete {{host}}/users/7
